test = {
    "type": "FeatureCollection",
    "query": ["1600", "pennsylvania", "ave", "nw", "washington", "dc", "20500"],
    "features": [
        {
            "id": "address.3807264357927334",
            "type": "Feature",
            "place_type": ["address"],
            "relevance": 1,
            "properties": {
                "accuracy": "rooftop",
                "mapbox_id": "dXJuOm1ieGFkcjoxYWIxM2EwYy00NGI4LTQyMGMtOGE0MS0wZmYyNDE3NjBlNDY",
            },
            "text": "Pennsylvania Avenue Northwest",
            "place_name": "1600 Pennsylvania Avenue Northwest, Washington, District of Columbia 20500, United States",
            "matching_place_name": "1600 Pennsylvania Avenue Northwest, Washington, DC 20500, United States",
            "center": [-77.036521, 38.897685],
            "geometry": {"type": "Point", "coordinates": [-77.036521, 38.897685]},
            "address": "1600",
            "context": [
                {
                    "id": "neighborhood.429993196",
                    "mapbox_id": "dXJuOm1ieHBsYzpHYUVzN0E",
                    "text": "National Mall",
                },
                {
                    "id": "postcode.63000300",
                    "mapbox_id": "dXJuOm1ieHBsYzpBOEZPN0E",
                    "text": "20500",
                },
                {
                    "id": "place.345549036",
                    "mapbox_id": "dXJuOm1ieHBsYzpGSmlvN0E",
                    "wikidata": "Q61",
                    "text": "Washington",
                },
                {
                    "id": "region.328940",
                    "mapbox_id": "dXJuOm1ieHBsYzpCUVRz",
                    "wikidata": "Q3551781",
                    "short_code": "US-DC",
                    "text": "District of Columbia",
                },
                {
                    "id": "country.8940",
                    "mapbox_id": "dXJuOm1ieHBsYzpJdXc",
                    "wikidata": "Q30",
                    "short_code": "us",
                    "text": "United States",
                },
            ],
        },
        {
            "id": "poi.592705513820",
            "type": "Feature",
            "place_type": ["poi"],
            "relevance": 0.813333,
            "properties": {
                "foursquare": "3fd66200f964a520d6f01ee3",
                "wikidata": "Q35525",
                "landmark": True,
                "address": "1600 Pennsylvania Ave NW",
                "category": "historic site, historic",
            },
            "text": "The White House",
            "place_name": "The White House, 1600 Pennsylvania Ave NW, Washington, District of Columbia 20500, United States",
            "matching_text": "1600 Pennsylvania Avenue",
            "matching_place_name": "1600 Pennsylvania Avenue, 1600 Pennsylvania Ave NW, Washington, DC 20500, United States",
            "center": [-77.036556, 38.8977365],
            "geometry": {"coordinates": [-77.036556, 38.8977365], "type": "Point"},
            "context": [
                {
                    "id": "neighborhood.429993196",
                    "mapbox_id": "dXJuOm1ieHBsYzpHYUVzN0E",
                    "text": "National Mall",
                },
                {
                    "id": "postcode.63000300",
                    "mapbox_id": "dXJuOm1ieHBsYzpBOEZPN0E",
                    "text": "20500",
                },
                {
                    "id": "place.345549036",
                    "mapbox_id": "dXJuOm1ieHBsYzpGSmlvN0E",
                    "wikidata": "Q61",
                    "text": "Washington",
                },
                {
                    "id": "region.328940",
                    "mapbox_id": "dXJuOm1ieHBsYzpCUVRz",
                    "wikidata": "Q3551781",
                    "short_code": "US-DC",
                    "text": "District of Columbia",
                },
                {
                    "id": "country.8940",
                    "mapbox_id": "dXJuOm1ieHBsYzpJdXc",
                    "wikidata": "Q30",
                    "short_code": "us",
                    "text": "United States",
                },
            ],
        },
        {
            "id": "poi.867583441398",
            "type": "Feature",
            "place_type": ["poi"],
            "relevance": 0.677778,
            "properties": {
                "foursquare": "4c28f397ce3fc92849fd6d88",
                "landmark": True,
                "address": "1101 Pennsylvania Ave NW",
                "category": "business, service, building",
            },
            "text": "1101 Pennsylvania Avenue NW",
            "place_name": "1101 Pennsylvania Avenue NW, 1101 Pennsylvania Ave NW, Washington, District of Columbia 20004, United States",
            "matching_place_name": "1101 Pennsylvania Avenue NW, 1101 Pennsylvania Ave NW, Washington, DC 20004, United States",
            "center": [-77.02741, 38.89527],
            "geometry": {"coordinates": [-77.02741, 38.89527], "type": "Point"},
            "context": [
                {
                    "id": "neighborhood.170716396",
                    "mapbox_id": "dXJuOm1ieHBsYzpDaXpzN0E",
                    "text": "Downtown",
                },
                {
                    "id": "postcode.60739308",
                    "mapbox_id": "dXJuOm1ieHBsYzpBNTdPN0E",
                    "text": "20004",
                },
                {
                    "id": "place.345549036",
                    "mapbox_id": "dXJuOm1ieHBsYzpGSmlvN0E",
                    "wikidata": "Q61",
                    "text": "Washington",
                },
                {
                    "id": "region.328940",
                    "mapbox_id": "dXJuOm1ieHBsYzpCUVRz",
                    "wikidata": "Q3551781",
                    "short_code": "US-DC",
                    "text": "District of Columbia",
                },
                {
                    "id": "country.8940",
                    "mapbox_id": "dXJuOm1ieHBsYzpJdXc",
                    "wikidata": "Q30",
                    "short_code": "us",
                    "text": "United States",
                },
            ],
        },
        {
            "id": "poi.1271310332647",
            "type": "Feature",
            "place_type": ["poi"],
            "relevance": 0.677778,
            "properties": {
                "foursquare": "4c2a115efe6e2d7f10c4553c",
                "landmark": True,
                "category": "business, service, building",
            },
            "text": "801 Pennsylvania Ave NW",
            "place_name": "801 Pennsylvania Ave NW, Washington, District of Columbia 20004, United States",
            "matching_place_name": "801 Pennsylvania Ave NW, Washington, DC 20004, United States",
            "center": [-77.023419, 38.89476],
            "geometry": {"coordinates": [-77.023419, 38.89476], "type": "Point"},
            "context": [
                {
                    "id": "neighborhood.170716396",
                    "mapbox_id": "dXJuOm1ieHBsYzpDaXpzN0E",
                    "text": "Downtown",
                },
                {
                    "id": "postcode.60739308",
                    "mapbox_id": "dXJuOm1ieHBsYzpBNTdPN0E",
                    "text": "20004",
                },
                {
                    "id": "place.345549036",
                    "mapbox_id": "dXJuOm1ieHBsYzpGSmlvN0E",
                    "wikidata": "Q61",
                    "text": "Washington",
                },
                {
                    "id": "region.328940",
                    "mapbox_id": "dXJuOm1ieHBsYzpCUVRz",
                    "wikidata": "Q3551781",
                    "short_code": "US-DC",
                    "text": "District of Columbia",
                },
                {
                    "id": "country.8940",
                    "mapbox_id": "dXJuOm1ieHBsYzpJdXc",
                    "wikidata": "Q30",
                    "short_code": "us",
                    "text": "United States",
                },
            ],
        },
        {
            "id": "address.4331768223432906",
            "type": "Feature",
            "place_type": ["address"],
            "relevance": 0.652063,
            "properties": {
                "accuracy": "rooftop",
                "mapbox_id": "dXJuOm1ieGFkcjpmOTYwMzc4OC01MWE4LTQ3NzQtOWVhMi1lM2ZkZGY0NWQ0OWI",
            },
            "text": "Pennsylvania Avenue Southeast",
            "place_name": "1600 Pennsylvania Avenue Southeast, Washington, District of Columbia 20003, United States",
            "matching_place_name": "1600 Pennsylvania Avenue Southeast, Washington, DC 20003, United States",
            "center": [-76.982024, 38.879243],
            "geometry": {"type": "Point", "coordinates": [-76.982024, 38.879243]},
            "address": "1600",
            "context": [
                {
                    "id": "neighborhood.89894124",
                    "mapbox_id": "dXJuOm1ieHBsYzpCVnVzN0E",
                    "text": "Capitol Hill",
                },
                {
                    "id": "postcode.60731116",
                    "mapbox_id": "dXJuOm1ieHBsYzpBNTZ1N0E",
                    "text": "20003",
                },
                {
                    "id": "place.345549036",
                    "mapbox_id": "dXJuOm1ieHBsYzpGSmlvN0E",
                    "wikidata": "Q61",
                    "text": "Washington",
                },
                {
                    "id": "region.328940",
                    "mapbox_id": "dXJuOm1ieHBsYzpCUVRz",
                    "wikidata": "Q3551781",
                    "short_code": "US-DC",
                    "text": "District of Columbia",
                },
                {
                    "id": "country.8940",
                    "mapbox_id": "dXJuOm1ieHBsYzpJdXc",
                    "wikidata": "Q30",
                    "short_code": "us",
                    "text": "United States",
                },
            ],
        },
    ],
    "attribution": "NOTICE: © 2024 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained. POI(s) provided by Foursquare.",
}
