{
    "type": "FeatureCollection",
    "query": ["san", "francisco", "ca"],
    "features": [
        {
            "id": "neighborhood.642780396",
            "type": "Feature",
            "place_type": ["neighborhood"],
            "relevance": 1,
            "properties": {
                "mapbox_id": "dXJuOm1ieHBsYzpKbEFNN0E",
                "wikidata": "Q956169",
            },
            "text": "The Castro",
            "place_name": "The Castro, San Francisco, California, United States",
            "bbox": [-122.4383698, 37.7542953, -122.4282707, 37.7628975],
            "center": [-122.435, 37.7546],
            "geometry": {"type": "Point", "coordinates": [-122.435, 37.7546]},
            "context": [
                {
                    "id": "postcode.312504044",
                    "mapbox_id": "dXJuOm1ieHBsYzpFcUJ1N0E",
                    "text": "94114",
                },
                {
                    "id": "place.292358380",
                    "mapbox_id": "dXJuOm1ieHBsYzpFVzBJN0E",
                    "wikidata": "Q62",
                    "text": "San Francisco",
                },
                {
                    "id": "district.20547308",
                    "mapbox_id": "dXJuOm1ieHBsYzpBVG1HN0E",
                    "wikidata": "Q62",
                    "text": "San Francisco County",
                },
                {
                    "id": "region.419052",
                    "mapbox_id": "dXJuOm1ieHBsYzpCbVRz",
                    "wikidata": "Q99",
                    "short_code": "US-CA",
                    "text": "California",
                },
                {
                    "id": "country.8940",
                    "mapbox_id": "dXJuOm1ieHBsYzpJdXc",
                    "wikidata": "Q30",
                    "short_code": "us",
                    "text": "United States",
                },
            ],
        },
        {
            "id": "neighborhood.97185004",
            "type": "Feature",
            "place_type": ["neighborhood"],
            "relevance": 1,
            "properties": {"mapbox_id": "dXJuOm1ieHBsYzpCY3JzN0E"},
            "text": "Cayuga Terrace",
            "place_name": "Cayuga Terrace, San Francisco, California, United States",
            "bbox": [-122.4465637, 37.7178307, -122.437355, 37.7237053],
            "center": [-122.441055, 37.72334],
            "geometry": {"type": "Point", "coordinates": [-122.441055, 37.72334]},
            "context": [
                {
                    "id": "postcode.312495852",
                    "mapbox_id": "dXJuOm1ieHBsYzpFcUJPN0E",
                    "text": "94112",
                },
                {
                    "id": "place.292358380",
                    "mapbox_id": "dXJuOm1ieHBsYzpFVzBJN0E",
                    "wikidata": "Q62",
                    "text": "San Francisco",
                },
                {
                    "id": "district.20547308",
                    "mapbox_id": "dXJuOm1ieHBsYzpBVG1HN0E",
                    "wikidata": "Q62",
                    "text": "San Francisco County",
                },
                {
                    "id": "region.419052",
                    "mapbox_id": "dXJuOm1ieHBsYzpCbVRz",
                    "wikidata": "Q99",
                    "short_code": "US-CA",
                    "text": "California",
                },
                {
                    "id": "country.8940",
                    "mapbox_id": "dXJuOm1ieHBsYzpJdXc",
                    "wikidata": "Q30",
                    "short_code": "us",
                    "text": "United States",
                },
            ],
        },
        {
            "id": "neighborhood.87239916",
            "type": "Feature",
            "place_type": ["neighborhood"],
            "relevance": 1,
            "properties": {"mapbox_id": "dXJuOm1ieHBsYzpCVE1zN0E"},
            "text": "Candlestick Point",
            "place_name": "Candlestick Point, San Francisco, California, United States",
            "bbox": [-122.3961868, 37.7083979, -122.374425, 37.7203852],
            "center": [-122.39484, 37.71104],
            "geometry": {"type": "Point", "coordinates": [-122.39484, 37.71104]},
            "context": [
                {
                    "id": "postcode.312667884",
                    "mapbox_id": "dXJuOm1ieHBsYzpFcUx1N0E",
                    "text": "94134",
                },
                {
                    "id": "place.292358380",
                    "mapbox_id": "dXJuOm1ieHBsYzpFVzBJN0E",
                    "wikidata": "Q62",
                    "text": "San Francisco",
                },
                {
                    "id": "district.20547308",
                    "mapbox_id": "dXJuOm1ieHBsYzpBVG1HN0E",
                    "wikidata": "Q62",
                    "text": "San Francisco County",
                },
                {
                    "id": "region.419052",
                    "mapbox_id": "dXJuOm1ieHBsYzpCbVRz",
                    "wikidata": "Q99",
                    "short_code": "US-CA",
                    "text": "California",
                },
                {
                    "id": "country.8940",
                    "mapbox_id": "dXJuOm1ieHBsYzpJdXc",
                    "wikidata": "Q30",
                    "short_code": "us",
                    "text": "United States",
                },
            ],
        },
        {
            "id": "neighborhood.96546028",
            "type": "Feature",
            "place_type": ["neighborhood"],
            "relevance": 1,
            "properties": {
                "mapbox_id": "dXJuOm1ieHBsYzpCY0VzN0E",
                "wikidata": "Q3296615",
            },
            "text": "Cathedral Hill",
            "place_name": "Cathedral Hill, San Francisco, California, United States",
            "bbox": [-122.426147461, 37.782654743, -122.420514855, 37.789166664],
            "center": [-122.42304, 37.785484],
            "geometry": {"type": "Point", "coordinates": [-122.42304, 37.785484]},
            "context": [
                {
                    "id": "postcode.312471276",
                    "mapbox_id": "dXJuOm1ieHBsYzpFcC91N0E",
                    "text": "94109",
                },
                {
                    "id": "place.292358380",
                    "mapbox_id": "dXJuOm1ieHBsYzpFVzBJN0E",
                    "wikidata": "Q62",
                    "text": "San Francisco",
                },
                {
                    "id": "district.20547308",
                    "mapbox_id": "dXJuOm1ieHBsYzpBVG1HN0E",
                    "wikidata": "Q62",
                    "text": "San Francisco County",
                },
                {
                    "id": "region.419052",
                    "mapbox_id": "dXJuOm1ieHBsYzpCbVRz",
                    "wikidata": "Q99",
                    "short_code": "US-CA",
                    "text": "California",
                },
                {
                    "id": "country.8940",
                    "mapbox_id": "dXJuOm1ieHBsYzpJdXc",
                    "wikidata": "Q30",
                    "short_code": "us",
                    "text": "United States",
                },
            ],
        },
        {
            "id": "neighborhood.81628396",
            "type": "Feature",
            "place_type": ["neighborhood"],
            "relevance": 0.702963,
            "properties": {"mapbox_id": "dXJuOm1ieHBsYzpCTjJNN0E"},
            "text": "Caballo Hills",
            "place_name": "Caballo Hills, Oakland, California, United States",
            "bbox": [-122.1759644, 37.7731282, -122.1405501, 37.7975578],
            "center": [-122.17475, 37.796898],
            "geometry": {"type": "Point", "coordinates": [-122.17475, 37.796898]},
            "context": [
                {
                    "id": "postcode.314314476",
                    "mapbox_id": "dXJuOm1ieHBsYzpFcndPN0E",
                    "text": "94619",
                },
                {
                    "id": "place.368830700",
                    "mapbox_id": "dXJuOm1ieHBsYzpGZnZvN0E",
                    "wikidata": "Q17042",
                    "text": "Oakland",
                },
                {
                    "id": "district.214764",
                    "mapbox_id": "dXJuOm1ieHBsYzpBMGJz",
                    "wikidata": "Q107146",
                    "text": "Alameda County",
                },
                {
                    "id": "region.419052",
                    "mapbox_id": "dXJuOm1ieHBsYzpCbVRz",
                    "wikidata": "Q99",
                    "short_code": "US-CA",
                    "text": "California",
                },
                {
                    "id": "country.8940",
                    "mapbox_id": "dXJuOm1ieHBsYzpJdXc",
                    "wikidata": "Q30",
                    "short_code": "us",
                    "text": "United States",
                },
            ],
        },
        {
            "id": "neighborhood.95816940",
            "type": "Feature",
            "place_type": ["neighborhood"],
            "relevance": 0.702963,
            "properties": {"mapbox_id": "dXJuOm1ieHBsYzpCYllNN0E"},
            "text": "Castlemont",
            "place_name": "Castlemont, Oakland, California, United States",
            "bbox": [-122.1703873, 37.7472763, -122.1579895, 37.7626762],
            "center": [-122.16126, 37.755337],
            "geometry": {"type": "Point", "coordinates": [-122.16126, 37.755337]},
            "context": [
                {
                    "id": "postcode.314207980",
                    "mapbox_id": "dXJuOm1ieHBsYzpFcnB1N0E",
                    "text": "94605",
                },
                {
                    "id": "place.368830700",
                    "mapbox_id": "dXJuOm1ieHBsYzpGZnZvN0E",
                    "wikidata": "Q17042",
                    "text": "Oakland",
                },
                {
                    "id": "district.214764",
                    "mapbox_id": "dXJuOm1ieHBsYzpBMGJz",
                    "wikidata": "Q107146",
                    "text": "Alameda County",
                },
                {
                    "id": "region.419052",
                    "mapbox_id": "dXJuOm1ieHBsYzpCbVRz",
                    "wikidata": "Q99",
                    "short_code": "US-CA",
                    "text": "California",
                },
                {
                    "id": "country.8940",
                    "mapbox_id": "dXJuOm1ieHBsYzpJdXc",
                    "wikidata": "Q30",
                    "short_code": "us",
                    "text": "United States",
                },
            ],
        },
        {
            "id": "neighborhood.86256876",
            "type": "Feature",
            "place_type": ["neighborhood"],
            "relevance": 0.702963,
            "properties": {"mapbox_id": "dXJuOm1ieHBsYzpCU1FzN0E"},
            "text": "Campolindo",
            "place_name": "Campolindo, Moraga, California, United States",
            "bbox": [-122.1418094, 37.8641583, -122.1239181, 37.8757178],
            "center": [-122.12611, 37.87226],
            "geometry": {"type": "Point", "coordinates": [-122.12611, 37.87226]},
            "context": [
                {
                    "id": "postcode.313839340",
                    "mapbox_id": "dXJuOm1ieHBsYzpFclRPN0E",
                    "text": "94556",
                },
                {
                    "id": "place.219850988",
                    "mapbox_id": "dXJuOm1ieHBsYzpEUnFvN0E",
                    "wikidata": "Q594122",
                    "text": "Moraga",
                },
                {
                    "id": "district.5129964",
                    "mapbox_id": "dXJuOm1ieHBsYzpUa2Jz",
                    "wikidata": "Q108058",
                    "text": "Contra Costa County",
                },
                {
                    "id": "region.419052",
                    "mapbox_id": "dXJuOm1ieHBsYzpCbVRz",
                    "wikidata": "Q99",
                    "short_code": "US-CA",
                    "text": "California",
                },
                {
                    "id": "country.8940",
                    "mapbox_id": "dXJuOm1ieHBsYzpJdXc",
                    "wikidata": "Q30",
                    "short_code": "us",
                    "text": "United States",
                },
            ],
        },
    ],
    "attribution": "NOTICE: © 2024 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained. POI(s) provided by Foursquare.",
}
